[profile.default]
src = "src"
out = "out"
test = "test/unit"
libs = ["dependencies"]
ast = true
solc = "0.8.30"

[profile.halmos]
test = "test/halmos"

[dependencies]
forge-std = "1.15.0"
"@openzeppelin-contracts" = "5.6.1"
a16z-halmos-cheatcodes = "6da4e692c357ba6d641a2e677a28298cac9f76ab"
