name: Aderyn

on: pull_request

jobs:
  check:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v6
          with:
            persist-credentials: false
  
        - uses: cachix/install-nix-action@v31
  
        - uses: cachix/cachix-action@v16
          with:
            name: devenv
  
        - name: Install devenv
          run: nix profile add nixpkgs#devenv
  
        - name: Activate devenv
          run: |
            eval "$(devenv print-dev-env)"
            echo "PATH=$PATH" >> "$GITHUB_ENV"
  
        - name: Install dependencies
          run: forge soldeer install

        - name: Aderyn Check
          uses: Cyfrin/aderyn-ci@v0
          with:
            fail-on: high
