name: Test

on: pull_request

jobs:
  check:
    name: Foundry Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        shell: devenv shell bash -- -e {0}
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: cachix/install-nix-action@v31

      - uses: cachix/cachix-action@v16
        with:
          name: devenv

      - name: Install devenv
        shell: bash
        run: nix profile add nixpkgs#devenv

      - name: Install dependencies
        run: forge soldeer install

      - name: Run Forge tests
        run: forge test -v
